package utils

const val IMPORT_COMPOSE_FOUNDATION: String = "import androidx.compose.foundation.*"
const val IMPORT_COMPOSE_LAYOUT_SIZE: String = "import androidx.compose.foundation.layout.*"
const val IMPORT_COMPOSE_MATERIAL: String = "import androidx.compose.material.*"
const val IMPORT_COMPOSE_UI: String = "import androidx.compose.ui.*"
const val IMPORT_COMPOSE_CONSTRAINT: String = "import androidx.constraintlayout.compose.*"
const val IMPORT_COMPOSE_COMPOSABLE: String = "import androidx.compose.runtime.Composable"
const val IMPORT_COMPOSE_PREVIEW: String = "import androidx.compose.ui.tooling.preview.Preview"
const val IMPORT_COMPOSE_UI_UNIT: String = "import androidx.compose.ui.unit.*"
const val IMPORT_COMPOSE_UI_RES: String = "import androidx.compose.ui.res.*"
const val IMPORT_COMPOSE_UI_TEXT_STYLE: String = "import androidx.compose.ui.text.style.*"
const val IMPORT_COMPOSE_UI_LAZY: String = "import androidx.compose.foundation.lazy.*"
const val IMPORT_COMPOSE_UI_LAZY_ITEMS: String = "import androidx.compose.foundation.lazy.items"
const val IMPORT_COMPOSE_UI_REMEMBER: String = "import androidx.compose.runtime.remember"
const val IMPORT_COMPOSE_GRAPHICS: String = "import androidx.compose.ui.graphics.*"
const val IMPORT_COMPOSE_NAV_HOST: String = "import androidx.navigation.compose.NavHost"
const val IMPORT_COMPOSE_NAV_COMPOSABLE: String = "import androidx.navigation.compose.composable"
const val IMPORT_COMPOSE_REMEMBER_NAV: String = "import androidx.navigation.compose.rememberNavController"
const val IMPORT_COMPOSE_NAV_ARG: String = "import androidx.navigation.navArgument"
const val IMPORT_COMPOSE_NAV_TYPE: String = "import androidx.navigation.NavType"
